
name: renovate

on:
  schedule:
    # Runs at 01:00 UTC every day
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      overrideSchedule:
        description: 'Force execution (bypass scheduling)'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string

jobs:
  renovate:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Check out repository code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: renovatebot/github-action@a889a8abcb11ef7feaafaf5e483ea01d4bf7774e # v43.0.5
        env:
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
          RENOVATE_ONBOARDING: "false"
          RENOVATE_CONFIG_FILE: ".github/renovate.json5"
          RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
        with:
          token: ${{ secrets.PAT }}
